name: Deploy to GitHub Pages

on:
  push:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Install dependencies
        run: npm install --legacy-peer-deps
      
      - name: List files before build
        run: ls -la
      
      - name: Build
        run: npm run build
      
      - name: List files after build
        run: |
          echo "Current directory:"
          ls -la
          echo "Checking for output directories:"
          ls -la dist 2>/dev/null || echo "No dist directory"
          ls -la build 2>/dev/null || echo "No build directory"
          ls -la out 2>/dev/null || echo "No out directory"
          ls -la .next 2>/dev/null || echo "No .next directory"
      
      - name: Create output directory if it doesn't exist
        run: mkdir -p out
      
      - name: Add .nojekyll file
        run: touch out/.nojekyll
      
      - name: Copy files to out directory if needed
        run: |
          if [ -d "dist" ] && [ ! -d "out" ]; then
            cp -r dist/* out/
          elif [ -d "build" ] && [ ! -d "out" ]; then
            cp -r build/* out/
          elif [ -d ".next" ] && [ ! -d "out" ]; then
            cp -r .next/* out/
          fi
      
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: out
          branch: gh-pages
          clean: true
